--AUTO INCREMENT FOR ID
CREATE TABLE unique_cats2 (
   cat_id INT NOT NULL AUTO_INCREMENT,
   name VARCHAR(100),
   age INT,
   PRIMARY KEY (cat_id)
);

-- USING DEFAULT VALUES IF THE VALUE IS NOT SPECIFIED
CREATE TABLE unique_cats2 (
   cat_id INT NOT NULL AUTO_INCREMENT,
   name VARCHAR(100),
   age INT DEFAULT 12,
   PRIMARY KEY (cat_id)
);
