-- // CREATING A TABLE AND DECLARING ITS HEADERS
-- CREATE TABLE <table name> (
-- 	Variable <variable type>,
-- Variable <variable type>,
-- Variable <variable type>
-- );

-- //PREVENTS THE USER FROM INSERTING EMPTY VARIABLES INTO TABLE
-- CREATE TABLE <table name> (
-- 	Variable <variable type> NOT NULL,
-- Variable <variable type> NOT NULL,
-- Variable <variable type> NOT NULL
-- );
